package org.irods.jargon.irodsext.mdtemplate.api;
/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

import io.swagger.annotations.*;

import org.irods.jargon.metadatatemplate.model.MDTemplate;
import org.irods.jargon.metadatatemplate.model.MDTemplateElement;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.UUID;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-07-24T19:53:50.811Z")

@Api(value = "template", description = "the template API")
public interface TemplateApi {

    @ApiOperation(value = "Create Element", nickname = "addElement", notes = "Add element for template.", tags={ "Element", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation") })
    @RequestMapping(value = "/template/{guid}/element",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> addElement(@ApiParam(value = "unique object task name",required=true) @PathVariable("guid") String guid,@ApiParam(value = "Created Element object" ,required=true )  @Valid @RequestBody MDTemplateElement body);


    @ApiOperation(value = "Add a new Template", nickname = "addTemplate", notes = "Adding a new metadata template", tags={ "Templates", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/template",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    UUID addTemplate(@ApiParam(value = "Template object that needs to be added to the system" ,required=true )  @Valid @RequestBody MDTemplate templateData);


    @ApiOperation(value = "Delete Element", nickname = "deleteElement", notes = "", tags={ "Element", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid guid supplied"),
        @ApiResponse(code = 404, message = "Element not found") })
    @RequestMapping(value = "/template/{guid}/element/{guid}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteElement(@ApiParam(value = "The Element that needs to be deleted",required=true) @PathVariable("guid") String guid);


    @ApiOperation(value = "Delete a Template", nickname = "deleteTemplate", notes = "", tags={ "Templates", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Template not found") })
    @RequestMapping(value = "/template/{guid}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<String> deleteTemplate(@ApiParam(value = "template guid to delete",required=true) @PathVariable("guid") String guid);


    @ApiOperation(value = "Get template by id", nickname = "findTemplateByGuid", notes = "By passing in the appropriate options, you can search for available templates ", tags={ "Templates", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "search results matching criteria"),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @RequestMapping(value = "/template/{guid}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<MDTemplate> findTemplateByGuid(@ApiParam(value = "pass an a guid to get template",required=true) @PathVariable("guid") String guid);


    @ApiOperation(value = "Get Element by guid", nickname = "getElementByGuid", notes = "", response = MDTemplateElement.class, tags={ "Element", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = MDTemplateElement.class),
        @ApiResponse(code = 400, message = "Invalid guid supplied"),
        @ApiResponse(code = 404, message = "Element not found") })
    @RequestMapping(value = "/template/{guid}/element/{guid}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<MDTemplateElement> getElementByGuid(@ApiParam(value = "The Element that needs to be fetched. ",required=true) @PathVariable("guid") String guid);


    @ApiOperation(value = "Updated Element", nickname = "updateElement", notes = "", tags={ "Element", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid Element supplied"),
        @ApiResponse(code = 404, message = "Element not found") })
    @RequestMapping(value = "/template/{guid}/element/{guid}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateElement(@ApiParam(value = "Element that need to be updated",required=true) @PathVariable("guid") String guid,@ApiParam(value = "Updated Element object" ,required=true )  @Valid @RequestBody MDTemplateElement body);


    @ApiOperation(value = "Update an existing Template", nickname = "updateTemplate", notes = "", tags={ "Templates", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Template not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/template",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    UUID updateTemplate(@ApiParam(value = "Template object that needs to be added to the system" ,required=true )  @Valid @RequestBody MDTemplate templateData);

}
